USE [master]
GO

/****** Object:  Database [isomessages]    Script Date: 2/28/2021 9:02:56 AM ******/
CREATE DATABASE [isomessages]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'isomessages', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\isomessages.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'isomessages_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\isomessages_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [isomessages] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [isomessages].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [isomessages] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [isomessages] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [isomessages] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [isomessages] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [isomessages] SET ARITHABORT OFF 
GO

ALTER DATABASE [isomessages] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [isomessages] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [isomessages] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [isomessages] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [isomessages] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [isomessages] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [isomessages] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [isomessages] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [isomessages] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [isomessages] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [isomessages] SET  DISABLE_BROKER 
GO

ALTER DATABASE [isomessages] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [isomessages] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [isomessages] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [isomessages] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [isomessages] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [isomessages] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [isomessages] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [isomessages] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [isomessages] SET  MULTI_USER 
GO

ALTER DATABASE [isomessages] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [isomessages] SET DB_CHAINING OFF 
GO

ALTER DATABASE [isomessages] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [isomessages] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [isomessages] SET  READ_WRITE 
GO


